// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ist.proto

package com.iflytek.tps.beans.core;

public final class IstOuterClass {
    private IstOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface IstRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ist.IstRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        int getSessionParamCount();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        boolean containsSessionParam(
                String key);

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getSessionParam();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        java.util.Map<String, String>
        getSessionParamMap();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        String getSessionParamOrDefault(
                String key,
                String defaultValue);

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        String getSessionParamOrThrow(
                String key);

        /**
         * <pre>
         * 音频数据
         * </pre>
         *
         * <code>bytes samples = 2;</code>
         */
        com.google.protobuf.ByteString getSamples();

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         */
        String getSamplesInfo();

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         */
        com.google.protobuf.ByteString
        getSamplesInfoBytes();

        /**
         * <pre>
         * 音频结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         */
        boolean getEndFlag();
    }

    /**
     * <pre>
     * 请求参数
     * </pre>
     * <p>
     * Protobuf type {@code ist.IstRequest}
     */
    public static final class IstRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ist.IstRequest)
            IstRequestOrBuilder {
        // Use IstRequest.newBuilder() to construct.
        private IstRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IstRequest() {
            samples_ = com.google.protobuf.ByteString.EMPTY;
            samplesInfo_ = "";
            endFlag_ = false;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private IstRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                sessionParam_ = com.google.protobuf.MapField.newMapField(
                                        SessionParamDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    sessionParam__ = input.readMessage(
                                    SessionParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            sessionParam_.getMutableMap().put(
                                    sessionParam__.getKey(), sessionParam__.getValue());
                            break;
                        }
                        case 18: {

                            samples_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            samplesInfo_ = s;
                            break;
                        }
                        case 32: {

                            endFlag_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return IstOuterClass.internal_static_ist_IstRequest_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetSessionParam();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return IstOuterClass.internal_static_ist_IstRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IstRequest.class, Builder.class);
        }

        private int bitField0_;
        public static final int SESSIONPARAM_FIELD_NUMBER = 1;

        private static final class SessionParamDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    IstOuterClass.internal_static_ist_IstRequest_SessionParamEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                String, String> sessionParam_;

        private com.google.protobuf.MapField<String, String>
        internalGetSessionParam() {
            if (sessionParam_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        SessionParamDefaultEntryHolder.defaultEntry);
            }
            return sessionParam_;
        }

        public int getSessionParamCount() {
            return internalGetSessionParam().getMap().size();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public boolean containsSessionParam(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            return internalGetSessionParam().getMap().containsKey(key);
        }

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getSessionParam() {
            return getSessionParamMap();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public java.util.Map<String, String> getSessionParamMap() {
            return internalGetSessionParam().getMap();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public String getSessionParamOrDefault(
                String key,
                String defaultValue) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetSessionParam().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public String getSessionParamOrThrow(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetSessionParam().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int SAMPLES_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString samples_;

        /**
         * <pre>
         * 音频数据
         * </pre>
         *
         * <code>bytes samples = 2;</code>
         */
        public com.google.protobuf.ByteString getSamples() {
            return samples_;
        }

        public static final int SAMPLESINFO_FIELD_NUMBER = 3;
        private volatile Object samplesInfo_;

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         */
        public String getSamplesInfo() {
            Object ref = samplesInfo_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                samplesInfo_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         */
        public com.google.protobuf.ByteString
        getSamplesInfoBytes() {
            Object ref = samplesInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                samplesInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ENDFLAG_FIELD_NUMBER = 4;
        private boolean endFlag_;

        /**
         * <pre>
         * 音频结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         */
        public boolean getEndFlag() {
            return endFlag_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetSessionParam(),
                            SessionParamDefaultEntryHolder.defaultEntry,
                            1);
            if (!samples_.isEmpty()) {
                output.writeBytes(2, samples_);
            }
            if (!getSamplesInfoBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, samplesInfo_);
            }
            if (endFlag_ != false) {
                output.writeBool(4, endFlag_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<String, String> entry
                    : internalGetSessionParam().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        sessionParam__ = SessionParamDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, sessionParam__);
            }
            if (!samples_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, samples_);
            }
            if (!getSamplesInfoBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, samplesInfo_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, endFlag_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof IstRequest)) {
                return super.equals(obj);
            }
            IstRequest other = (IstRequest) obj;

            boolean result = true;
            result = result && internalGetSessionParam().equals(
                    other.internalGetSessionParam());
            result = result && getSamples()
                    .equals(other.getSamples());
            result = result && getSamplesInfo()
                    .equals(other.getSamplesInfo());
            result = result && (getEndFlag()
                    == other.getEndFlag());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetSessionParam().getMap().isEmpty()) {
                hash = (37 * hash) + SESSIONPARAM_FIELD_NUMBER;
                hash = (53 * hash) + internalGetSessionParam().hashCode();
            }
            hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
            hash = (53 * hash) + getSamples().hashCode();
            hash = (37 * hash) + SAMPLESINFO_FIELD_NUMBER;
            hash = (53 * hash) + getSamplesInfo().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static IstRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IstRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static IstRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static IstRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static IstRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IstRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(IstRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 请求参数
         * </pre>
         * <p>
         * Protobuf type {@code ist.IstRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ist.IstRequest)
                IstRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return IstOuterClass.internal_static_ist_IstRequest_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return IstOuterClass.internal_static_ist_IstRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IstRequest.class, Builder.class);
            }

            // Construct using com.iflytek.ist.sdk.core.IstOuterClass.IstRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                internalGetMutableSessionParam().clear();
                samples_ = com.google.protobuf.ByteString.EMPTY;

                samplesInfo_ = "";

                endFlag_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return IstOuterClass.internal_static_ist_IstRequest_descriptor;
            }

            public IstRequest getDefaultInstanceForType() {
                return IstRequest.getDefaultInstance();
            }

            public IstRequest build() {
                IstRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public IstRequest buildPartial() {
                IstRequest result = new IstRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.sessionParam_ = internalGetSessionParam();
                result.sessionParam_.makeImmutable();
                result.samples_ = samples_;
                result.samplesInfo_ = samplesInfo_;
                result.endFlag_ = endFlag_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof IstRequest) {
                    return mergeFrom((IstRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(IstRequest other) {
                if (other == IstRequest.getDefaultInstance()) return this;
                internalGetMutableSessionParam().mergeFrom(
                        other.internalGetSessionParam());
                if (other.getSamples() != com.google.protobuf.ByteString.EMPTY) {
                    setSamples(other.getSamples());
                }
                if (!other.getSamplesInfo().isEmpty()) {
                    samplesInfo_ = other.samplesInfo_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                IstRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (IstRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.MapField<
                    String, String> sessionParam_;

            private com.google.protobuf.MapField<String, String>
            internalGetSessionParam() {
                if (sessionParam_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                return sessionParam_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMutableSessionParam() {
                onChanged();
                ;
                if (sessionParam_ == null) {
                    sessionParam_ = com.google.protobuf.MapField.newMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                if (!sessionParam_.isMutable()) {
                    sessionParam_ = sessionParam_.copy();
                }
                return sessionParam_;
            }

            public int getSessionParamCount() {
                return internalGetSessionParam().getMap().size();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public boolean containsSessionParam(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                return internalGetSessionParam().getMap().containsKey(key);
            }

            /**
             * Use {@link #getSessionParamMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, String> getSessionParam() {
                return getSessionParamMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public java.util.Map<String, String> getSessionParamMap() {
                return internalGetSessionParam().getMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public String getSessionParamOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetSessionParam().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public String getSessionParamOrThrow(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetSessionParam().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearSessionParam() {
                internalGetMutableSessionParam().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder removeSessionParam(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableSessionParam() {
                return internalGetMutableSessionParam().getMutableMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            public Builder putSessionParam(
                    String key,
                    String value) {
                if (key == null) {
                    throw new NullPointerException();
                }
                if (value == null) {
                    throw new NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder putAllSessionParam(
                    java.util.Map<String, String> values) {
                internalGetMutableSessionParam().getMutableMap()
                        .putAll(values);
                return this;
            }

            private com.google.protobuf.ByteString samples_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             */
            public com.google.protobuf.ByteString getSamples() {
                return samples_;
            }

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             */
            public Builder setSamples(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                samples_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             */
            public Builder clearSamples() {

                samples_ = getDefaultInstance().getSamples();
                onChanged();
                return this;
            }

            private Object samplesInfo_ = "";

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             */
            public String getSamplesInfo() {
                Object ref = samplesInfo_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    samplesInfo_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             */
            public com.google.protobuf.ByteString
            getSamplesInfoBytes() {
                Object ref = samplesInfo_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    samplesInfo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             */
            public Builder setSamplesInfo(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                samplesInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             */
            public Builder clearSamplesInfo() {

                samplesInfo_ = getDefaultInstance().getSamplesInfo();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             */
            public Builder setSamplesInfoBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                samplesInfo_ = value;
                onChanged();
                return this;
            }

            private boolean endFlag_;

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:ist.IstRequest)
        }

        // @@protoc_insertion_point(class_scope:ist.IstRequest)
        private static final IstRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new IstRequest();
        }

        public static IstRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<IstRequest>
                PARSER = new com.google.protobuf.AbstractParser<IstRequest>() {
            public IstRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new IstRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<IstRequest> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<IstRequest> getParserForType() {
            return PARSER;
        }

        public IstRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface IstResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ist.IstResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        String getErrStr();

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        com.google.protobuf.ByteString
        getErrStrBytes();

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        int getErrCode();

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         */
        String getAnsStr();

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         */
        com.google.protobuf.ByteString
        getAnsStrBytes();

        /**
         * <pre>
         * 识别结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         */
        boolean getEndFlag();
    }

    /**
     * <pre>
     * 识别结果
     * </pre>
     * <p>
     * Protobuf type {@code ist.IstResult}
     */
    public static final class IstResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ist.IstResult)
            IstResultOrBuilder {
        // Use IstResult.newBuilder() to construct.
        private IstResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IstResult() {
            errStr_ = "";
            errCode_ = 0;
            ansStr_ = "";
            endFlag_ = false;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private IstResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            errStr_ = s;
                            break;
                        }
                        case 16: {

                            errCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            ansStr_ = s;
                            break;
                        }
                        case 32: {

                            endFlag_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return IstOuterClass.internal_static_ist_IstResult_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return IstOuterClass.internal_static_ist_IstResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IstResult.class, Builder.class);
        }

        public static final int ERRSTR_FIELD_NUMBER = 1;
        private volatile Object errStr_;

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public String getErrStr() {
            Object ref = errStr_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public com.google.protobuf.ByteString
        getErrStrBytes() {
            Object ref = errStr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ERRCODE_FIELD_NUMBER = 2;
        private int errCode_;

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        public int getErrCode() {
            return errCode_;
        }

        public static final int ANSSTR_FIELD_NUMBER = 3;
        private volatile Object ansStr_;

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         */
        public String getAnsStr() {
            Object ref = ansStr_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ansStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         */
        public com.google.protobuf.ByteString
        getAnsStrBytes() {
            Object ref = ansStr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ansStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ENDFLAG_FIELD_NUMBER = 4;
        private boolean endFlag_;

        /**
         * <pre>
         * 识别结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         */
        public boolean getEndFlag() {
            return endFlag_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getErrStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errStr_);
            }
            if (errCode_ != 0) {
                output.writeInt32(2, errCode_);
            }
            if (!getAnsStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ansStr_);
            }
            if (endFlag_ != false) {
                output.writeBool(4, endFlag_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getErrStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errStr_);
            }
            if (errCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errCode_);
            }
            if (!getAnsStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ansStr_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, endFlag_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof IstResult)) {
                return super.equals(obj);
            }
            IstResult other = (IstResult) obj;

            boolean result = true;
            result = result && getErrStr()
                    .equals(other.getErrStr());
            result = result && (getErrCode()
                    == other.getErrCode());
            result = result && getAnsStr()
                    .equals(other.getAnsStr());
            result = result && (getEndFlag()
                    == other.getEndFlag());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
            hash = (53 * hash) + getErrStr().hashCode();
            hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrCode();
            hash = (37 * hash) + ANSSTR_FIELD_NUMBER;
            hash = (53 * hash) + getAnsStr().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static IstResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IstResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IstResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IstResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static IstResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static IstResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static IstResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IstResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(IstResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 识别结果
         * </pre>
         * <p>
         * Protobuf type {@code ist.IstResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ist.IstResult)
                IstResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return IstOuterClass.internal_static_ist_IstResult_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return IstOuterClass.internal_static_ist_IstResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IstResult.class, Builder.class);
            }

            // Construct using com.iflytek.ist.sdk.core.IstOuterClass.IstResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errStr_ = "";

                errCode_ = 0;

                ansStr_ = "";

                endFlag_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return IstOuterClass.internal_static_ist_IstResult_descriptor;
            }

            public IstResult getDefaultInstanceForType() {
                return IstResult.getDefaultInstance();
            }

            public IstResult build() {
                IstResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public IstResult buildPartial() {
                IstResult result = new IstResult(this);
                result.errStr_ = errStr_;
                result.errCode_ = errCode_;
                result.ansStr_ = ansStr_;
                result.endFlag_ = endFlag_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof IstResult) {
                    return mergeFrom((IstResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(IstResult other) {
                if (other == IstResult.getDefaultInstance()) return this;
                if (!other.getErrStr().isEmpty()) {
                    errStr_ = other.errStr_;
                    onChanged();
                }
                if (other.getErrCode() != 0) {
                    setErrCode(other.getErrCode());
                }
                if (!other.getAnsStr().isEmpty()) {
                    ansStr_ = other.ansStr_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                IstResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (IstResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object errStr_ = "";

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public String getErrStr() {
                Object ref = errStr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    errStr_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public com.google.protobuf.ByteString
            getErrStrBytes() {
                Object ref = errStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    errStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStr(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder clearErrStr() {

                errStr_ = getDefaultInstance().getErrStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errStr_ = value;
                onChanged();
                return this;
            }

            private int errCode_;

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public int getErrCode() {
                return errCode_;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder setErrCode(int value) {

                errCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder clearErrCode() {

                errCode_ = 0;
                onChanged();
                return this;
            }

            private Object ansStr_ = "";

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             */
            public String getAnsStr() {
                Object ref = ansStr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ansStr_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             */
            public com.google.protobuf.ByteString
            getAnsStrBytes() {
                Object ref = ansStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ansStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             */
            public Builder setAnsStr(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ansStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             */
            public Builder clearAnsStr() {

                ansStr_ = getDefaultInstance().getAnsStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             */
            public Builder setAnsStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ansStr_ = value;
                onChanged();
                return this;
            }

            private boolean endFlag_;

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:ist.IstResult)
        }

        // @@protoc_insertion_point(class_scope:ist.IstResult)
        private static final IstResult DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new IstResult();
        }

        public static IstResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<IstResult>
                PARSER = new com.google.protobuf.AbstractParser<IstResult>() {
            public IstResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new IstResult(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<IstResult> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<IstResult> getParserForType() {
            return PARSER;
        }

        public IstResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ist_IstRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ist_IstRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ist_IstRequest_SessionParamEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ist_IstRequest_SessionParamEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ist_IstResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ist_IstResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\tIst.proto\022\003ist\"\261\001\n\nIstRequest\0227\n\014sessi" +
                        "onParam\030\001 \003(\0132!.ist.IstRequest.SessionPa" +
                        "ramEntry\022\017\n\007samples\030\002 \001(\014\022\023\n\013samplesInfo" +
                        "\030\003 \001(\t\022\017\n\007endFlag\030\004 \001(\010\0323\n\021SessionParamE" +
                        "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"M\n\t" +
                        "IstResult\022\016\n\006errStr\030\001 \001(\t\022\017\n\007errCode\030\002 \001" +
                        "(\005\022\016\n\006ansStr\030\003 \001(\t\022\017\n\007endFlag\030\004 \001(\01029\n\003I" +
                        "st\0222\n\tcreateRec\022\017.ist.IstRequest\032\016.ist.I" +
                        "stResult\"\000(\0010\001B\032\n\030com.iflytek.ist.sdk.co" +
                        "reb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_ist_IstRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ist_IstRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ist_IstRequest_descriptor,
                new String[]{"SessionParam", "Samples", "SamplesInfo", "EndFlag",});
        internal_static_ist_IstRequest_SessionParamEntry_descriptor =
                internal_static_ist_IstRequest_descriptor.getNestedTypes().get(0);
        internal_static_ist_IstRequest_SessionParamEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ist_IstRequest_SessionParamEntry_descriptor,
                new String[]{"Key", "Value",});
        internal_static_ist_IstResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ist_IstResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ist_IstResult_descriptor,
                new String[]{"ErrStr", "ErrCode", "AnsStr", "EndFlag",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
